<?php

function annonce_theme($existing, $type, $theme, $path) {
  return [
    'annonce' => [
      'file' => 'annonce.page.inc',
      'render element' => 'elements'
      //'template' => 'annonce',
      //'variables' => ['count' => 0, 'node' => NULL],
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_annonce().
 */
function annonce_theme_suggestions_annonce(array $variables) {
  $suggestions[] = "annonce__" . $variables['elements']['#view_mode'];
  return $suggestions;
}